# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160916_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='ordermodel',
        ),
    ]
