# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160916_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='value',
            field=models.IntegerField(default=5),
        ),
    ]
