# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_ordermodel_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('n', 'Snacks'), ('d', 'Drinks'), ('u', 'Unorderable'), ('s', 'Sweats and Deserts')], max_length=14)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
