# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160916_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='menumodel',
        ),
    ]
