# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20160917_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favemodel',
            old_name='favorite',
            new_name='fave',
        ),
    ]
