# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20160917_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favemodel',
            new_name='usersettings',
        ),
    ]
