# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20160918_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersettings',
            new_name='usersetting',
        ),
    ]
