# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signedup',
            field=models.BooleanField(default=False),
        ),
    ]
